### PR TITLE
App Themes & Colors

### PR DESCRIPTION
**Pull request by VinuBalagopalAP**

### CODE REVIEW

**Comment by evolvingkid** [comment]
@VinuBalagopalAP 

its better to add dependency inject to the color class.

**Comment by evolvingkid** [comment]
@VinuBalagopalAP  also follow folder structure themes have a folder in core/themes

**Comment by evolvingkid** [comment]
@VinuBalagopalAP  also push the code to dev branch

**Comment by DanBrown47** [comment]
@VinuBalagopalAP Requesting a change of branch

**Pull request closed without merging**
